### DISCUSSION TITLE
Gradients support for HRs

### DISCUSSION THREAD

**Discussion by tabs-not-spaces** [dracula/dracula-ui#117] [Ideas]
Should be a simple enough one, but the ability to implement the gradient classes onto horizontal rules would... rule.

I've already implemented this myself by abstracting out my own css elements. Obviously it would need further work to follow the style in use.

```CSS
.drac-hr-bg-yellow-pink {
    background: var(--yellow-pink);
    height: 2px;
    border: 0;
}
.drac-hr-bg-pink-purple {
    background: var(--pink-purple);
    height: 2px;
    border: 0;
}
```
