### ISSUE TITLE
add yarn setup instructions

### ISSUE THREAD

**Issue by tedbyron** [dracula/dracula-ui#122]
Instead of using a `.npmrc`, if already using yarn you can just add something like this to `.yarnrc.yml` (yarn 2/3):

```yaml
npmScopes:
  dracula:
    npmAlwaysAuth: true
    npmAuthToken: ${TOKEN}
    npmRegistryServer: https://npm.pkg.github.com/
```
