### ISSUE TITLE
OrderedList does not respect "type" attribute

### ISSUE THREAD

**Issue by drewwyatt** [dracula/dracula-ui#129]
`OrderedList` appears to be setting `list-style` to `none` (via `.drac-list`), which causes the [`type` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol#attr-type) to not work. 

e.g. when applying `type="a"` (for lowercase letters), the list still renders numbers.

**Comment by Insidiae** [comment]
From what I understand after a quick scan of the `OrderedList` styles, Dracula UI implements its own list styles for the `OrderedList` component, hence why there's a `list-style: none` on `.drac-list`. The list numbers are then basically re-implemented via a CSS `counter()`. Fortunately, I think we can get other numbering types by [passing in another parameter to that `counter()` function](https://developer.mozilla.org/en-US/docs/Web/CSS/counter#counter-style)!

The additional parameter for `counter()` is the same as a `list-style-type` property, which we can use in our `OrderedList` to get the same effect as the `<ol>`'s `type` attribute.

In the spirit of Hacktoberfest, I took my shot at trying to solve this issue! I think we can modify [`src/styles/list.css`](https://github.com/dracula/dracula-ui/blob/main/src/styles/list.css#L20) to accept a CSS variable as a second argument to the `counter()` function:

```css
.list-ordered li::before {
  content: counter(li, var(--type, decimal))'.';
  /* the rest of the styles remain the same... */
}
```

Then we can create additional classes to set that `--type` variable. For example:

```css
.list-ordered-lower-alpha {
  --type: lower-alpha;
}

.list-ordered-upper-alpha {
  --type: upper-alpha;
}
```

And then for the React component, we can also accept a `type` prop and then set one of the additional classes accordingly:

```ts
const orderedListTypes = {
  1: 'drac-list-ordered-decimal',
  a: 'drac-list-ordered-lower-alpha',
  A: 'drac-list-ordered-lower-alpha',
  i: 'drac-list-ordered-lower-roman',
  I: 'drac-list-ordered-lower-roman'
}
```

This is a temporary fix until we are able to have [case-sensitive attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#attr_operator_value_s). Ideally we should be able to set the `--type` variable depending on the `type` attribute of the `OrderedList` component:

```css
.list-ordered[type="a" s] {
  --type: lower-alpha;
}

.list-ordered[type="A" s] {
  --type: upper-alpha;
}
```

But that method only works on Firefox as of now, and for other browsers the `type` attribute selector is always case insensitive, resulting the styles for `.list-ordered[type="a"]` conflicting with `.list-ordered[type="A"]`.
