### ISSUE TITLE
Allow tweaking the default values with css variables

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [dracula/dracula-ui#149]
I'd love to see an extra layer of indirection in the CSS variables.

For instance, I don't wish to add `rounded="none"` to every single `<Box/>`; nor do I want to add the additional boilerplate to wrap each element with my own versions using different defaults.

At the moment, I'm using the hacky global addition of:

```css
:root {
   --rounded-lg: 0;
}
```

Unfortunately, that solution means I now _cannot_ have a `rounded="lg"` box _at all_. Not a great solution, I know ...

I'd love it if the default value for `.drac-box` were, say, `border-radius: var(--drac-default-rounded)`, and then `--drac-default-rounded` were defined as `var(--rounded-lg)`; this would allow me to customize the 'defaults' of various values for one's own site:

```css
:root {
   --drac-default-rounded: var(--rounded-none);
   --drac-default-anchor-color: var(--color-pink);
}
```
